# Generated by Django 3.2.7 on 2021-11-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_restau', models.CharField(max_length=200)),
                ('image_restau', models.ImageField(blank=True, null=True, upload_to='')),
                ('rue_restau', models.CharField(max_length=200)),
                ('ville_restau', models.CharField(max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product')),
            ],
        ),
    ]
